function [xDot, yDot ,thetaDot ,deltaDot ,lambdaXDot ,lambdaYDot ,lambdaThetaDot ,lambdaDeltaDot ] = replaceDifferentialEquations(xDot, yDot ,thetaDot ,deltaDot ,lambdaXDot ,lambdaYDot ,lambdaThetaDot ,lambdaDeltaDot ,predTheta ,predDelta ,predLambdaX ,predLambdaY ,predLambdaTheta ,predLambdaDelta)
%% Replace differential equations by free function components
symvar(xDot)
xDot = subs(xDot,symvar(xDot),{predDelta predLambdaDelta predLambdaTheta predLambdaX predLambdaY ...
      predTheta});
yDot = subs(yDot,symvar(yDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
thetaDot = subs(thetaDot,symvar(thetaDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
deltaDot = subs(deltaDot,symvar(deltaDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
lambdaXDot= subs(lambdaXDot,symvar(lambdaXDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
lambdaYDot = subs(lambdaYDot,symvar(lambdaYDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
lambdaThetaDot = subs(lambdaThetaDot,symvar(lambdaThetaDot),{predTheta predDelta predLambdaX predLambdaY ...
    predLambdaTheta predLambdaDelta});
lambdaDeltaDot = subs(lambdaDeltaDot,symvar(lambdaDeltaDot),{predTheta predDelta predLambdaX predLambdaY ...
    predTheta predLambdaDelta});
symvar(xDot)


end